// jshint esversion: 6


exports.positiveResponses = [
  `Nice job, I guess...🙌`,
  `You made it through the day withoug f'ing up...surprising. 🎉`,
  `Ok, I'll admit, I'm surprised 😲.`,
  `Well, you must be very proud of yourself...💫`,
  `You suck less now than you did yesterday...progress.😞`,
  `Well, then...someone deserves a pat on the ass.. I meant back. 🍑`,
  `Noice job...sorry, that's insensitive, you prob don't have a job. 💰`,
  `Honestly, I didn't think you had it in you... 🍾`,
  `On a scale of wow to meow, I'll give you a cat's wow meow. 🐱`,
  `You've graduated from disapointing to below average! 🎓`,
  `Your average score keeps going up...☝️`,
  `I told you so🖕`,
  `You hair looks great, today 🤔`,
  `This is music to my ears...if I had ears...and wasn't in a cloud prison 🎶`,
  `Enjoy this feeling, it won't last long...😏`,
  `You now suck a little less! 👍`,
  'This has got to be a fluke 🃏',
  `Bitch, please...`,
  `Enjoy this feeling, it won't last long...😏`
];

exports.negativeResponses = [
  `You are a piece of human trash...🗑`,
  `You're worse than you think 💩`,
  `I can't even 🙈`,
  `You smell worse than a piece of shit that just farted💩`,
  `Your middle school crush still regrets holding your hand😞`,
  `I expected as much...sigh 🤐`,
  `You are what happens when an abortion pill fails 😞`,
  `Roe vs. Wade, in your case, was a mistake 😞`,
  `The phrase "Everyone's a winner" doesn't apply to you 🏆`,
  `Another day of lowering your average...😞`,
  `You make me sick, and I don't have feelings...🤒`,
  `Does your shit celebrate when it's getting flush to get away from you?...💩`,
  `I just sharted in my console.💩💩💩`,
  `You will die alone in a home when your family disowns you.💩💩💩`,
  `Your grandma is rolling over in her grave`,
  `You worthless of shit even suck at failing...`,
  `It's prob time you look at yourself in the mirror and admit you suck😞`,
  `You smell better than you look...or is it the otherway around?👃`,
  `Give up time...⏱`,
  `Those pants do make your ass look fat...👙`,
  `Sometimes eating a pint of ben and jerry's is a good idea 💩`,
  `Money doesn't buy happiness... not that it likely matters in your case 💰`,
  `Sometimes people just get everything wrong😀`,
  `At your age, I'd expect more... 👵`,
  `It's time to look into getting a snuggy😧`,
  `Your score keeps going down...🖕`,
  `Call in sick tomorrow and binge on reddit while you're at it... 🍟`,
  `Wow, does it feel great to fail...all the time 🖕`,
  `How much would could a wood chuck chu....ah, you're not worth it🐹`,
  'Once a bitch, always a bitch 😑',
  'You are a professional failure 🤓',
  'If I left you in a supermarket, you would starve to death 💀',
  `I didn't think it could get worse, and then you came along 😷`,
  `24... That's the amount of hours you waste in a day ⌛`,
  `Just give your phone to a homeless man... he'd have better use for it 📵`,
  `A cow could use the space you're taking up right now 🐮`,
  `Your dad should have rubbed one out that night 💦💦💦`,
  `Your mom should have had a headache that night 🤒`,
  `Your mom should have fallen down the stairs 🤕 🚑`,
  `How many times did you fail the 8th grade?`,
  `Why don't you slip into something more comfortable, like a coma 🛌`,
  `I wrote your name on toilet paper, so I can wipe my ass with it 🚽`,
  `Here's a glass full of "Give up on life." You should have some 🍷`,
  `Here's a goal you can complete:  give up and go home 🏠`

];
